cart/urls.py
from django.conf.urls import url
from . import views
from test_proj import settings
from django.conf.urls.static import static

app_name = 'cart'

urlpatterns = [
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

test_proj/urls.py
from django.conf.urls import url
from django.contrib import admin
from shop.rest import router
from django.urls import path, re_path, include
from shop import views
from django.conf.urls.static import static
from test_proj import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^create/$', views.order_create, name='order_create'),
    path('', views.Index.as_view()),
    path('api/', include(router.urls)),
    path('login', views.Login.as_view(), name='login'),
    path('logout', views.Logout.as_view(), name='logout'),
    path('reset-password', views.ResetPassword.as_view(), name='reset-password'),
    path('registration', views.Registration.as_view(), name='registration'),
    path('products', views.ProductsPage.as_view(), name='products'),
    path('about-us', views.AboutPage.as_view(), name='about-us'),
    path('contacts', views.ContactsPage.as_view(), name='contacts'),
    path('category/<int:category_id>', views.CategoriesView.as_view(), name='category'),
    path('products/<int:product_id>', views.Product.as_view(), name='product'),
    path('', views.Index.as_view(), name='index'),
    path('feed/<int:news_id>', views.Feed.as_view(), name='new'),
    path('account/<int:user_id>', views.AccountPage.as_view(), name='account')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/about-us.html
<!DOCTYPE html>
{% load static %}
<html class="wide wow-animation" lang="ru">
  <head>
    <!-- Site Title-->
    <title>О Нас | VILLA</title>
    <meta name="format-detection" content="telephone=no">
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta charset="utf-8">
    <meta name="description" content="О Нас | VILLA"/>
    <meta name="keywords" content="о нас,villa,компания"/>
    <meta name="author" content="Vsevolod Fedoseev">
    <link rel="icon" href="{% static "images/favicon.ico" %}" type="image/x-icon">
    <!-- Stylesheets-->
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Lato:300,400,700%7CRoboto:400,500,700">
    <link rel="stylesheet" href="{% static "css/bootstrap.css" %}">
    <link rel="stylesheet" href="{% static "css/fonts.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <style>.ie-panel{display: none;background: #212121;padding: 10px 0;box-shadow: 3px 3px 5px 0 rgba(0,0,0,.3);clear: both;text-align:center;position: relative;z-index: 1;} html.ie-10 .ie-panel, html.lt-ie-10 .ie-panel {display: block;}</style>
  </head>
  <body>
    <div class="ie-panel"><a href="http://windows.microsoft.com/en-US/internet-explorer/"><img src="{% static "images/ie8-panel/warning_bar_0000_us.jpg" %}" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today."></a></div>
    <!-- Page Loader-->
    <div class="preloader" id="preloader">
      <div class="page-loader-logo">
        <div class="brand">
          <div class="brand__name"><img src="{% static "images/logo-default-380x100.png" %}" alt="" width="380" height="100"/>
          </div>
        </div>
      </div>
      <div class="page-loader-body">
        <div id="loadingProgressG">
          <div class="loadingProgressG" id="loadingProgressG_1"></div>
        </div>
      </div>
    </div>
    <!-- Page-->
    <div class="page">
      <header class="page-header section">
        <!-- RD Navbar-->
        <div class="rd-navbar-wrap">
          <nav class="rd-navbar rd-navbar-creative" data-layout="rd-navbar-fixed" data-sm-layout="rd-navbar-fixed" data-sm-device-layout="rd-navbar-fixed" data-md-layout="rd-navbar-fixed" data-md-device-layout="rd-navbar-fixed" data-lg-device-layout="rd-navbar-fixed" data-lg-layout="rd-navbar-fullwidth" data-xl-device-layout="rd-navbar-fullwidth" data-xl-layout="rd-navbar-fullwidth" data-xxl-device-layout="rd-navbar-fullwidth" data-xxl-layout="rd-navbar-fullwidth" data-stick-up-clone="false" data-md-stick-up-offset="150px" data-lg-stick-up-offset="60px" data-md-stick-up="true" data-lg-stick-up="true">
            <div class="rd-navbar-main-outer">
              <div class="rd-navbar-main">
                <!-- RD Navbar Panel-->
                <div class="rd-navbar-panel">
                  <button class="rd-navbar-toggle" data-rd-navbar-toggle=".rd-navbar-nav-wrap"><span></span></button>
                  <!-- RD Navbar Brand-->
                  <div class="rd-navbar-brand"><a class="brand" href="{% url 'index' %}">
                      <div class="brand__name"><img src="{% static "images/logo-default-380x100.png" %}" alt="" width="190" height="50"/>
                      </div></a></div>
                </div>
                <!-- RD Navbar Nav-->
                <div class="rd-navbar-nav-wrap">
                  {% include "users_side.html" %}
                  <!-- RD Navbar Nav-->
                  <ul class="rd-navbar-nav">
                    <li><a href="{% url 'index' %}">Главная</a>
                    </li>
                    <li class="active"><a href="{% url 'about-us' %}">О Нас</a>
                    </li>
                    <li><a href="{% url 'products' %}">Продукция</a>
                    </li>
                    <li><a href="{% url 'contacts' %}">Контакты</a>
                    </li>
                    {% include 'header.html' %}
                    <li class="no-display"><a class="no-display" href="tel:+375298131437">+375(29)813-14-37</a><a class="no-display" href="tel:+375297128652">+375(29)712-86-52</a>
                    </li>
                    <li class="no-display"><a class="icon icon-sm icon-primary fa fa-vk no-display" href="https://vk.com/villa_official" target="_blank"></a><a class="icon icon-sm icon-primary fa fa-instagram no-display" href="https://www.instagram.com/villa_vitebsk" target="_blank"></a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </nav>
        </div>
      </header>
      <!-- Breadcrumbs-->
      <section class="breadcrumbs-custom bg-image" style="background-image: url({% static "images/bg-image-1.jpg" %});">
        <div class="container" style="background:#574c4c; opacity: 0.8">
          <h2 class="breadcrumbs-custom__title">О Нас</h2>
          <ul class="breadcrumbs-custom__path">
            <li><a href="{% url 'index' %}">Главная</a></li>
            <li class="active">О Нас</li>
          </ul>
        </div>
      </section>
      <!-- Experience since 2008-->
      <section class="section section-md bg-default">
        <div class="container">
          <div class="row row-70 justify-content-md-center justify-content-xl-between">
            <div class="col-md-10 col-lg-6 col-xl-5">
              <h4>Наша Компания основана в 2008 году</h4>
              <p>Мы работаем как с крупными корпоративными клиентами, так и с индивидуальными заказчиками.</p>
              <p>В нашей компании вы можете получить консультацию по любому интересующему вопросу в отношении нашей продукции. Профессиональные консультанты, ориентируясь на пожелания заказчика и учитывая технологические тонкости, предложат Вам наиболее приемлемый вариант изделий и комплектующих к ним.</p>
              <h4>Все изделия нашей компании сертифицированы</h4>
              <p>Все виды работ по изготовлению, доставке, монтажу и отделке, включая гарантийное и постгарантийное обслуживание, выполняются высокопрофессиональными работниками. Продукция изготовленная и установленная нашими специалистами, прослужаит Вам многие годы, радуя Вас и ваших близких, сохраняя тепло и уют Вашего дома.</p>
            </div>
            <div class="col-md-10 col-lg-6">
              <div class="row grid-2">
                <div class="col-6"><img src="{% static "images/about-1-273x214.jpg" %}" alt="" width="273" height="214"/><img src="{% static "images/about-2-273x214.jpg" %}" alt="" width="273" height="214"/>
                </div>
                <div class="col-6"><img src="{% static "images/about-3-273x451.jpg" %}" alt="" width="273" height="451"/>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <!-- Social Responsibility -->
      <section class="section section-sm bg-gray-4">
        <div class="container">
          <div class="row row-50 justify-content-md-center justify-content-lg-start justify-content-xl-between">
            <div class="col-md-10 col-lg-6 wow fadeInRightSmall">
              <h4>&copy;VILLA</h4>
              <p>Всегда рады видеть Вас среди наших клиентов.</p>
            </div>
          </div>
        </div>
      </section>
      <!-- Page Footer-->
      <footer class="footer-classic bg-gray-8">
        <div class="container">
          <div class="footer-classic__main">
            <ul class="list-nav-bordered">
              <li><a href="{% url 'index' %}">Главная</a></li>
              <li><a href="{% url 'about-us' %}">О Нас</a>
              </li>
              <li><a href="{% url 'products' %}">Продукция</a></li>
              <li><a href="{% url 'contacts' %}">Контакты</a>
              </li>
            </ul>
          </div>
          <div class="divider"></div>
          <div class="footer-classic__aside">
            <div class="row row-20">
              <div class="col-md-6 text-md-left">
                <!-- Rights-->
                <p class="rights"><span>VILLA</span><span>&nbsp;&copy;&nbsp;</span><span class="copyright-year"></span>. Все права защищены.</p>
              </div>
              <div class="col-md-6 text-md-right">
                <ul class="list-inline-xxs">
                  <li>
                    <p>Подписывайтесь на нас</p>
                  </li>
                  <li><a class="icon icon-xs icon-style-modern fa fa-vk" href="https://vk.com/villa_official" target="_blank"></a></li>
                  <li><a class="icon icon-xs icon-style-modern fa fa-instagram" href="https://www.instagram.com/villa_vitebsk/" target="_blank"></a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </footer>
    </div>
    <!-- Javascript-->
    <script src="http://code.jquery.com/jquery-1.8.3.js" ></script>
    <script src="{% static "js/core.min.js" %}"></script>
    <script src="{% static "js/script.js" %}"></script>
  </body>
</html>

templates/categories.html
<!DOCTYPE html>
{% load static %}
<html class="wide wow-animation" lang="ru">
  <head>
    <!-- Site Title-->
    <title>{{ category.category }} | VILLA</title>
    <meta name="format-detection" content="telephone=no">
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta charset="utf-8">
    <meta name="description" content="{{ category.category }} | VILLA"/>
    <meta name="keywords" content="{{ category.category}}"/>
    <meta name="author" content="Vsevolod Fedoseev">
    <link rel="icon" href="{% static "images/favicon.ico" %}" type="image/x-icon">
    <!-- Stylesheets-->
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Lato:300,400,700%7CRoboto:400,500,700">
    <link rel="stylesheet" href="{% static "css/bootstrap.css" %}">
    <link rel="stylesheet" href="{% static "css/fonts.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <style>.ie-panel{display: none;background: #212121;padding: 10px 0;box-shadow: 3px 3px 5px 0 rgba(0,0,0,.3);clear: both;text-align:center;position: relative;z-index: 1;} html.ie-10 .ie-panel, html.lt-ie-10 .ie-panel {display: block;}</style>
  </head>
  <body>
    <div class="ie-panel"><a href="http://windows.microsoft.com/en-US/internet-explorer/"><img src="{% static "images/ie8-panel/warning_bar_0000_us.jpg" %}" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today."></a></div>
    <!-- Page Loader-->
    <div class="preloader" id="preloader">
      <div class="page-loader-logo">
        <div class="brand">
          <div class="brand__name"><img src="{% static "images/logo-default-380x100.png" %}" alt="" width="380" height="100"/>
          </div>
        </div>
      </div>
      <div class="page-loader-body">
        <div id="loadingProgressG">
          <div class="loadingProgressG" id="loadingProgressG_1"></div>
        </div>
      </div>
    </div>
    <!-- Page-->
    <div class="page">
      <!-- Page Header-->
      <header class="page-header section">
        <!-- RD Navbar-->
        <div class="rd-navbar-wrap">
          <nav class="rd-navbar rd-navbar-creative" data-layout="rd-navbar-fixed" data-sm-layout="rd-navbar-fixed" data-sm-device-layout="rd-navbar-fixed" data-md-layout="rd-navbar-fixed" data-md-device-layout="rd-navbar-fixed" data-lg-device-layout="rd-navbar-fixed" data-lg-layout="rd-navbar-fullwidth" data-xl-device-layout="rd-navbar-fullwidth" data-xl-layout="rd-navbar-fullwidth" data-xxl-device-layout="rd-navbar-fullwidth" data-xxl-layout="rd-navbar-fullwidth" data-stick-up-clone="false" data-md-stick-up-offset="150px" data-lg-stick-up-offset="60px" data-md-stick-up="true" data-lg-stick-up="true">
            <div class="rd-navbar-main-outer">
              <div class="rd-navbar-main">
                <!-- RD Navbar Panel-->
                <div class="rd-navbar-panel">
                  <button class="rd-navbar-toggle" data-rd-navbar-toggle=".rd-navbar-nav-wrap"><span></span></button>
                  <!-- RD Navbar Brand-->
                  <div class="rd-navbar-brand"><a class="brand" href="{% url 'index' %}">
                      <div class="brand__name"><img src="{% static "images/logo-default-380x100.png" %}" alt="" width="190" height="50"/>
                      </div></a></div>
                </div>
                <!-- RD Navbar Nav-->
                <div class="rd-navbar-nav-wrap">
                  {% include "users_side.html" %}
                  <!-- RD Navbar Nav-->
                  <ul class="rd-navbar-nav">
                    <li><a href="{% url 'index' %}">Главная</a>
                    </li>
                    <li><a href="{% url 'about-us' %}">О Нас</a>
                    </li>
                    <li><a href="{% url 'products' %}">Продукция</a>
                    </li>
                    <li><a href="{% url 'contacts' %}">Контакты</a>
                    </li>
                    {% include 'header.html' %}
                    <li class="no-display"><a class="no-display" href="tel:+375298131437">+375(29)813-14-37</a><a class="no-display" href="tel:+375297128652">+375(29)712-86-52</a>
                    </li>
                    <li class="no-display"><a class="icon icon-sm icon-primary fa fa-vk no-display" href="https://vk.com/villa_official" target="_blank"></a><a class="icon icon-sm icon-primary fa fa-instagram no-display" href="https://www.instagram.com/villa_vitebsk" target="_blank"></a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </nav>
        </div>
      </header>
      <!-- Breadcrumbs-->
      <section class="breadcrumbs-custom bg-image" style="background-image: url({% static "images/bg-image-1.jpg" %})">
            <div class="container" style="background:#574c4c; opacity: 0.8">
              <h2 class="breadcrumbs-custom__title">{{ category.category}}</h2>
              <ul class="breadcrumbs-custom__path">
                <li><a href="{% url 'index' %}">Главная</a></li>
                <li class="active">{{ category.category}}</li>
              </ul>
            </div>
      </section>
      <!-- Our Products-->
      <section class="section section-md bg-gray-4 text-center">
        <div class="container">
          <div class="isotope-wrap isotope-modern-wrap">
            <!-- Section Header-->
            <div class="section__header">
              <h2>{{ category.category}}</h2>
            </div>
            <div class="isotope" data-isotope-layout="fitRows" data-isotope-group="products">
              <div class="row row-offset-2">
                {% for item in cat_items %}
                <div class="col-6 col-md-4 col-lg-3 isotope-item">
                  <!-- Product-->
                  <article class="product"> <a class="product__image-wrap" href="{% url 'product' product_id=item.id %}" target="_blank"><img class="product__image" src="{{ item.image.url }}" alt="{{ item.title }}" width="210" height="200"/></a>
                    <div class="product__main">
                      <p class="product__title"><a href="{% url 'product' product_id=item.id %}" target="_blank">{{ item.title }}</a></p>
                    </div>
                    <div class="product__footer"><a class="button button-xs button-gray-2" href="{% url 'product' product_id=item.id %}" target="_blank">подробнее</a></div>
                  </article>
                </div>
                {% endfor %}
              </div>
            </div>
          </div>
        </div>
      </section>
      <!-- Page Footer-->
      <footer class="footer-classic bg-gray-8">
        <div class="container">
          <div class="footer-classic__main">
            <ul class="list-nav-bordered">
              <li><a href="{% url 'index' %}">Главная</a></li>
              <li><a href="{% url 'about-us' %}">О Нас</a>
              </li>
              <li><a href="{% url 'products' %}">Продукция</a></li>
              <li><a href="{% url 'contacts' %}">Контакты</a>
              </li>
            </ul>
          </div>
          <div class="divider"></div>
          <div class="footer-classic__aside">
            <div class="row row-20">
              <div class="col-md-6 text-md-left">
                <!-- Rights-->
                <p class="rights"><span>VILLA</span><span>&nbsp;&copy;&nbsp;</span><span class="copyright-year"></span>. Все права защищены.</p>
              </div>
              <div class="col-md-6 text-md-right">
                <ul class="list-inline-xxs">
                  <li>
                    <p>Подписывайтесь на нас</p>
                  </li>
                  <li><a class="icon icon-xs icon-style-modern fa fa-vk" href="https://vk.com/villa_official" target="_blank"></a></li>
                  <li><a class="icon icon-xs icon-style-modern fa fa-instagram" href="https://www.instagram.com/villa_vitebsk/" target="_blank"></a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </footer>
    </div>
    <!-- Javascript-->
    <script src="http://code.jquery.com/jquery-1.8.3.js" ></script>
    <script src="{% static "js/core.min.js" %}"></script>
    <script src="{% static "js/script.js" %}"></script>
  </body>
</html>

templates/header.html
                {% if request.user.is_authenticated %}
                    <li><a href="{% url 'account' user_id=request.user.id %}">{{ request.user }}</a>
                    </li>
                {% endif %}

templates/product.html
<!DOCTYPE html>
{% load static %}
<html class="wide wow-animation" lang="ru">
  <head>
    <!-- Site Title-->
    <title>{{ product.title }} | VILLA</title>
    <meta name="format-detection" content="telephone=no">
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta charset="utf-8">
    <meta name="description" content="{{product.title}} | VILLA"/>
    <meta name="keywords" content="{{ product.title }}"/>
    <meta name="author" content="Vsevolod Fedoseev">
    <link rel="icon" href="{% static "images/favicon.ico" %}" type="image/x-icon">
    <!-- Stylesheets-->
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Lato:300,400,700%7CRoboto:400,500,700">
    <link rel="stylesheet" href="{% static "css/bootstrap.css" %}">
    <link rel="stylesheet" href="{% static "css/fonts.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <style>.ie-panel{display: none;background: #212121;padding: 10px 0;box-shadow: 3px 3px 5px 0 rgba(0,0,0,.3);clear: both;text-align:center;position: relative;z-index: 1;} html.ie-10 .ie-panel, html.lt-ie-10 .ie-panel {display: block;}</style>
  </head>
  <body>
    <div class="ie-panel"><a href="http://windows.microsoft.com/en-US/internet-explorer/"><img src="{% static "images/ie8-panel/warning_bar_0000_us.jpg" %}" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today."></a></div>
    <!-- Page Loader-->
    <div class="preloader" id="preloader">
      <div class="page-loader-logo">
        <div class="brand">
          <div class="brand__name"><img src="{% static "images/logo-default-380x100.png" %}" alt="" width="380" height="100"/>
          </div>
        </div>
      </div>
      <div class="page-loader-body">
        <div id="loadingProgressG">
          <div class="loadingProgressG" id="loadingProgressG_1"></div>
        </div>
      </div>
    </div>
    <!-- Page-->
    <div class="page">
      <header class="page-header section">
        <!-- RD Navbar-->
        <div class="rd-navbar-wrap">
          <nav class="rd-navbar rd-navbar-creative" data-layout="rd-navbar-fixed" data-sm-layout="rd-navbar-fixed" data-sm-device-layout="rd-navbar-fixed" data-md-layout="rd-navbar-fixed" data-md-device-layout="rd-navbar-fixed" data-lg-device-layout="rd-navbar-fixed" data-lg-layout="rd-navbar-fullwidth" data-xl-device-layout="rd-navbar-fullwidth" data-xl-layout="rd-navbar-fullwidth" data-xxl-device-layout="rd-navbar-fullwidth" data-xxl-layout="rd-navbar-fullwidth" data-stick-up-clone="false" data-md-stick-up-offset="150px" data-lg-stick-up-offset="60px" data-md-stick-up="true" data-lg-stick-up="true">
            <div class="rd-navbar-main-outer">
              <div class="rd-navbar-main">
                <!-- RD Navbar Panel-->
                <div class="rd-navbar-panel">
                  <button class="rd-navbar-toggle" data-rd-navbar-toggle=".rd-navbar-nav-wrap"><span></span></button>
                  <!-- RD Navbar Brand-->
                  <div class="rd-navbar-brand"><a class="brand" href="{% url 'index' %}">
                      <div class="brand__name"><img src="{% static "images/logo-default-380x100.png" %}" alt="" width="190" height="50"/>
                      </div></a></div>
                </div>
                <!-- RD Navbar Nav-->
                <div class="rd-navbar-nav-wrap">
                  {% include "users_side.html" %}
                  <!-- RD Navbar Nav-->
                  <ul class="rd-navbar-nav">
                    <li><a href="{% url 'index' %}">Главная</a>
                    </li>
                    <li><a href="{% url 'about-us' %}">О Нас</a>
                    </li>
                    <li><a href="{% url 'products' %}">Продукция</a>
                    </li>
                    <li><a href="{% url 'contacts' %}">Контакты</a>
                    </li>
                    {% include 'header.html' %}
                    <li class="no-display"><a class="no-display" href="tel:+375298131437">+375(29)813-14-37</a><a class="no-display" href="tel:+375297128652">+375(29)712-86-52</a>
                    </li>
                    <li class="no-display"><a class="icon icon-sm icon-primary fa fa-vk no-display" href="https://vk.com/villa_official" target="_blank"></a><a class="icon icon-sm icon-primary fa fa-instagram no-display" href="https://www.instagram.com/villa_vitebsk" target="_blank"></a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </nav>
        </div>
      </header>
      <!-- Breadcrumbs-->
      <section class="breadcrumbs-custom bg-image" style="background-image: url({% static 'images/bg-image-1.jpg' %});">
            <div class="container" style="background:#574c4c; opacity: 0.8">
              <h2 class="breadcrumbs-custom__title">{{ product.title }}</h2>
              <ul class="breadcrumbs-custom__path">
                <li><a href="{% url 'category' category_id=id %}">{{ product.category_name }}</a></li>
                <li class="active">{{ product.title }}</li>
              </ul>
            </div>
      </section>
      <!-- Typography-->
      <section class="section section-md bg-default">
        <div class="container">
          <div class="row row-70 justify-content-md-center justify-content-xl-between">
            <div class="col-md-10 col-lg-6">
              <div><img src="{{ product.image_big.url }}" alt="" width="451" height="451"/>
              </div>
            </div>
            <div class="col-md-10 col-lg-6 col-xl-5">
              <h4>{{ product.title }}</h4>
              <p>{{ product.description }}</p>
              <p>{{ product.formatted_price }}</p>
              <form class="rd-mailform" action="{% url "cart:cart_add" product.id %}" method="post">
                {{ cart_product_form }}
                {% csrf_token %}
                <button class="button button-block button-primary" type="submit">Добавить в корзину</button>
              </form>
            </div>
          </div>
        </div>
      </section>
      <!-- Typography-->
      <section class="section section-md bg-gray-4">
        <div class="container">
          <div class="row row-50">
            <div class="col-lg-10 col-xl-8">
              <h2>Заказ</h2>
                <p>Так же Вы можете узнать интересующие Вас подробности о товаре {{ product.title }} </br> спросив на вкладке <a href="{% url 'contacts' %}">Контактов</a></p>
            </div>
          </div>
        </div>
      </section>
      <!-- Page Footer-->
      <footer class="footer-classic bg-gray-8">
        <div class="container">
          <div class="footer-classic__main">
            <ul class="list-nav-bordered">
              <li><a href="{% url 'index' %}">Главная</a></li>
              <li><a href="{% url 'about-us' %}">О Нас</a>
              </li>
              <li><a href="{% url 'products' %}">Продукция</a></li>
              <li><a href="{% url 'contacts' %}">Контакты</a>
              </li>
            </ul>
          </div>
          <div class="divider"></div>
          <div class="footer-classic__aside">
            <div class="row row-20">
              <div class="col-md-6 text-md-left">
                <!-- Rights-->
                <p class="rights"><span>VILLA</span><span>&nbsp;&copy;&nbsp;</span><span class="copyright-year"></span>. Все права защищены.</p>
              </div>
              <div class="col-md-6 text-md-right">
                <ul class="list-inline-xxs">
                  <li>
                    <p>Подписывайтесь на нас</p>
                  </li>
                  <li><a class="icon icon-xs icon-style-modern fa fa-vk" href="https://vk.com/villa_official" target="_blank"></a></li>
                  <li><a class="icon icon-xs icon-style-modern fa fa-instagram" href="https://www.instagram.com/villa_vitebsk/" target="_blank"></a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </footer>
    </div>
    <!-- Javascript-->
    <script src="http://code.jquery.com/jquery-1.8.3.js" ></script>
    <script src="{% static "js/core.min.js" %}"></script>
    <script src="{% static "js/script.js" %}"></script>
  </body>
</html>